### ISSUE TITLE
Cob transaction

### ISSUE THREAD

**Issue by munrocket** [cobinhood/jobs#7]
Hello! I have one strange issue.
I sent COB token from my wallet to COB smart contract address accidentally :(
Can you return my funds? It's really big money for me. I can throw you a reward for this work.

Here accidental transaction from etherdelta:
https://etherscan.io/tx/0x970bbc74966f674c2c8ab5951bbe2c54b140056c9866dc098cfa65ab4e810c9b
And here my wallet address: 0xC62652C4b4a221e910D407D8EBCC8Bc75AFB55b5

**Comment by hitripod** [comment]
cobinhood.zendesk.com
